---
title: "Assignment 10.2 on Logistic Regression Model (Thoracic Surgery and Binary Classifier Data) "
author: "Basak Atanu"
date: 05-17-2022
output:
  
  pdf_document: default
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r, echo=TRUE}
library(foreign)

setwd("C:\\Users\\atanu\\Documents\\BellevueUniversity_MSDS\\DSC520\\Repository\\dsc520_")
thoraric <- read.arff("data\\ThoraricSurgery.arff")
#head(thoraric)
```

### lets fit the logistic regression model.
```{r}
model <- glm(Risk1Yr ~ DGN + PRE4 + PRE5 + PRE6 + PRE7 + + PRE8 + PRE9 + PRE10 + PRE11 + 
               PRE14 + PRE17 + PRE19 + PRE25 + PRE30 + PRE32 + AGE, data=thoraric, family='binomial')
summary(model)
```
### according to the summary, PRE9 (Dyspnoea before surgery), PRE14: T in clinical TNM - size of the original tumour with OC14 which means large size of tumour have greater affect on servical rate.

```{r}
res <- predict(model, thoraric, type='response')
confmatrix <- table(actual_value=thoraric$Risk1Yr, predicted_value = res>0.5)
```
### Accuracy
```{r}
(confmatrix[[1,1]] + confmatrix[[2,2]]) /  sum(confmatrix)
```
### Reading binary classifier data.
```{r}
setwd("C:\\Users\\atanu\\Documents\\BellevueUniversity_MSDS\\DSC520\\Repository\\dsc520_")
classifier_data <- read.csv("data\\binary-classifier-data.csv")

```
### Fitting logicstic regression model.
```{r}
model <- glm(label ~ x + y, data=classifier_data, family='binomial')
summary(model)
```
### Accuracy of logistic regression classifier.
```{r}
res <- predict(model, classifier_data, type='response')
confmatrix <- table(actual_value=classifier_data$label, predicted_value = res>0.5)
(confmatrix[[1,1]] + confmatrix[[2,2]]) /  sum(confmatrix)


```

